services:
  server:
    image: 'nginx:stable-alpine'
    ports: 
      - '8000:8080'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  php:
    
  # mysql:
  # composer:
  # npm:
  # artisan